### ISSUE TITLE
exception

### ISSUE THREAD

**Issue by asylvz** [paudano/kestrel#6]
Hi, trying to use Kestrel with the command below. But after 2-3 days of processing for 5x coverage dataset, I get the error below. Any idea? 

Thanks...

**java -Xmx16G -jar kestrel.jar -r human_g1k_v37.fasta simu5x_lane0.read1.fq simu5x_lane0.read2.fq -o dnm.vcf**

13:59:42 [KestrelRunner] ERROR e.g.kestrel.runner.KestrelRunner - Unexpected exception in run(): 249250591 (ArrayIndexOutOfBoundsException)
java.lang.ArrayIndexOutOfBoundsException: 249250591
        at edu.gatech.kestrel.activeregion.ActiveRegionDetector.getCounts(ActiveRegionDetector.java:1631)
        at edu.gatech.kestrel.activeregion.ActiveRegionDetector.getActiveRegions(ActiveRegionDetector.java:401)
        at edu.gatech.kestrel.runner.KestrelRunner.exec(KestrelRunner.java:286)
        at edu.gatech.kanalyze.KAnalyzeRunnable.run(KAnalyzeRunnable.java:156)
        at java.lang.Thread.run(Thread.java:748)

**Comment by paudano** [comment]
Looks like this may be a bug handling ambiguous bases. It's failing building the array of k-mer counts for chromosome 1 (249250621 - 31 + 1 = 249250591).

Running Kestrel on human samples is going to generate a lot of false calls in and around repeats. You can get some useful calls with 48-mers, but 31 is too small. Try 48-mers and see if that gets around this for now. I have run hg38 with 48-mers in the past.
